# This file is generated by django-cms ansible installer ({{ template_run_date }})
#!/bin/sh

killall -9 mysqld_safe
killall -9 mysqld
sleep 3

mysqld_safe --skip-grant-tables --skip-syslog &

sleep 5

echo "use mysql;update user set password=PASSWORD('{{ mysql_root_password }}') where User='root';flush privileges;" | mysql -uroot
sleep 3

killall -9 mysqld_safe
killall -9 mysqld
sleep 3