########## DataBases
##################### MySQL

  - name: (MySQL) install common packages
    apt: name={{ item }} state=present
    with_items:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
    # when: db == 'mysql'

  - name: (MySQL) install python dependencies
    pip: name={{ item }} state=present
    with_items:
      - MySQL-python
    # when: db == 'mysql'

  - name: (MySQL) ensure MySQL is started
    service: name=mysql state=started enabled=yes
    # when: db == 'mysql'

  - stat: path=/root/.my.cnf
    register: my_cnf_exist

  - name: (MySQL) create /root/.my.cnf file with root password credentials
    template: >
      src=../../templates/my.cnf
      dest=/root/.my.cnf
      owner=root
      mode=0600
    when: my_cnf_exist.stat.exists == False
    # when: db == 'mysql'

    # For clean installations
  - name: (MySQL) set mysql root password for all root accounts
    mysql_user: >
      name=root
      host={{ item }}
      password={{ mysql_root_password }}
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
    when: my_cnf_exist.stat.exists == False
  #   # when: db == 'mysql'